# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MintProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  # Pods for MintProject

  target 'MintProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MintProjectUITests' do
    # Pods for testing
  end

end
